apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: persons.people.com
spec:
  group: people.com
  scope: Namespaced
  names:
    singular: person
    plural: persons
    kind: Person
    shortNames:
      - pp
    listKind: PersonList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                age: 
                  type: integer
