apiVersion: v1
kind: Pod
metadata:
  name: blue
  namespace: learning
spec:
  containers:
    - name: blue-container
      image: nginx
  tolerations:
    - key: type
      value: A
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node
              values:
                - A
              operator: In

