apiVersion: v1
kind: Pod
metadata:
  name: green
  namespace: learning
spec:
  containers:
    - name: green-container
      image: nginx
  tolerations:
    - key: type
      value: C
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node
              values:
                - C
              operator: In
