apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
  namespace: learning
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: /secrets
  volumes:
    - name: secrets
      secret:
        secretName: credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: learning
data:
  USERNAME: dXNlcm5hbWUK
  PASSWORD: cGFzc3dvcmQK