apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    type: router-dep
spec:
  template:
    metadata:
      name: router-pod
      labels:
        type: router
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: router

