apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: learning
spec:
  limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 200m
      min:
        cpu: 100m
      max:
        cpu: "1"
      type: Container
