apiVersion: v1
kind: ResourceQuota
metadata:
  name: leanring-rs
  namespace: learning
  labels:
spec:
  hard:
    pods: 6
    requests.cpu: 2
    requests.memory: 2Gi
    limits.cpu: 4
    limits.memory: 4Gi
