apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: learning
spec:
  limits:
    - default:
        memory: 400Mi
      defaultRequest:
        memory: 200Mi
      min:
        memory: 100Mi
      max:
        memory: 1Gi
      type: Container
