apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    app: voting-service
spec:
  type: NodePort
  ports:
    - name: "voting-port"
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    app: voting
