apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  namespace: learning
spec:
  selector:
    matchLabels:
      app: frontend
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
