apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-storageclass
  namespace: learning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: hostpath