apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    type: router-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    type: router