apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: learning
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: learning
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: default
roleRef:
  name: developer
  kind: Role
  apiGroup: rbac.authorization.k8s.io
