apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader-role
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "create"
      - "list"
      - "delete"
      - "watch"
      - "get"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-reader-rolebinding
subjects: 
  - kind: ServiceAccount
    name: node-admin
    namespace: learning
roleRef:
  name: node-reader-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-admin

