apiVersion: v1
kind: PersistentVolume
metadata:
  name: multinode-pv
  namespace: learning  # does not matter. PVs are created irrespective of namespace
spec:
  #  nodeAffinity:
  #    required:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: node
  #              values:
  #                - C
  #              operator: In
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /shared
    type: DirectoryOrCreate
