apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: learning  # does not matter. PVs are created irrespective of namespace
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /shared