apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: learning
rules:
  - apiGroups: 
      - ""
    resources:
      - "pods"
    verbs: 
      - "list"
      - "get"
      - "create"
      - "delete"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
  namespace: learning
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: learning
roleRef:
  name: pod-reader-role
  kind: Role