apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: learning
spec:
  automountServiceAccountToken: false
  serviceAccountName: pod-reader-sa
  containers:
    - name: nginx
      image: nginx
    