apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: learning
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: service-token
          mountPath: /secrets
  automountServiceAccountToken: false
  serviceAccountName: pod-reader-sa
  volumes:
    - name: service-token
      projected:
        sources:
          - serviceAccountToken:
              path: token-sa
    