apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-pvc
  labels:
    type: busybox
  namespace: learning
spec:
  containers:
    - name: busybox
      image: nginx
      volumeMounts:
        - name: nginx-pvc
          mountPath: /shared
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: nginx-pvc
  nodeSelector:
    node: B
