apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    type: router
  namespace: learning
spec:
  serviceAccount: nginx-sa
  initContainers:
    - name: busybox-1
      image: busybox
      command:
        - sh
        - -c
        - echo "Hello from busybox1. Going to sleep"; sleep 60; echo "busybox-1 wokeup!!!"
    - name: busybox-2
      image: busybox
      command:
        - sh
        - -c
        - echo "Hellow from busybox2. Going to sleep"; sleep 70; echo "busybox-2 wokeup!!!"
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: mysql-db-secret
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          memory: 1Gi
          cpu: 1
