apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    type: router-2
spec:
  containers:
    - name: nginx2
      image: nginx
  nodeSelector:
    type: control

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-2-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: router-2

