apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-pvc
  labels:
    type: router
  namespace: learning
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-pvc
          mountPath: /shared
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: nginx-pvc
