apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    type: router
  namespace: learning
spec:
  serviceAccount: nginx-sa
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: mysql-db-secret
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          memory: 4Gi
          cpu: 2
