apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: learning
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: pod-info
          mountPath: /info/pod
        - name: container-info
          mountPath: /info/container
  volumes:
    - name: pod-info
      downwardAPI:
        items:
          - path: pod_name
            fieldRef:
              fieldPath: metadata.name
          - path: pod_namespace
            fieldRef:
              fieldPath: metadata.namespace
    - name: container-info
      downwardAPI:
        items:
          - path: cpu_req
            resourceFieldRef:
              containerName: nginx
              resource: requests.cpu


