apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: db
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
  volumes:
    - name: db-data
      emptyDir: {}