apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    type: memory-db
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          name: redis
      volumeMounts:
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-data
      emptyDir: {}

