apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    app: voting
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
          name: voting-app-port